name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Ensures sequential execution of this workflow
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  CC: /usr/lib/ccache/gcc
  CXX: /usr/lib/ccache/g++

jobs:
  build-and-test:
    runs-on: buildjet-16vcpu-ubuntu-2204
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
          - jazzy
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:core-common-devel
          - rosdistro: jazzy
            container: ros:jazzy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show disk space before the tasks
        run: df -h

      - name: Show machine specs
        run: lscpu && free -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Use ros2-testing packages
        run: |
          if [ "${{ matrix.rosdistro }}" = "jazzy" ]; then
            sed -i 's|http://packages.ros.org/ros2/ubuntu|http://packages.ros.org/ros2-testing/ubuntu|g' /etc/apt/sources.list.d/ros2-latest.list
            apt-get update
          fi
        shell: bash

      - name: Create ccache directory
        run: |
          if [ -z "${CCACHE_DIR}" ]; then
            apt-get update
            apt-get install -y ccache
            export CCACHE_DIR=/root/.ccache
          fi
          mkdir -p ${CCACHE_DIR}
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Attempt to restore ccache
        uses: actions/cache/restore@v4
        with:
          path: |
            /root/.ccache
          key: ccache-main-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.sha }}
          restore-keys: |
            ccache-main-${{ runner.arch }}-${{ matrix.rosdistro }}-

      - name: Limit ccache size
        run: |
          rm -f "${CCACHE_DIR}/ccache.conf"
          echo -e "# Set maximum cache size\nmax_size = 600MB" >> "${CCACHE_DIR}/ccache.conf"
        shell: bash

      - name: Show ccache stats before build and reset stats
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
          ccache --zero-stats
        shell: bash

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-pre-command: taskset --cpu-list 0-6
          underlay-workspace: /opt/autoware

      - name: Show ccache stats after build
        run: du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Push the ccache cache
        uses: actions/cache/save@v4
        with:
          path: |
            /root/.ccache
          key: ccache-main-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.sha }}

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          underlay-workspace: /opt/autoware

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v5
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
          flags: total
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show disk space after the tasks
        run: df -h
